import type { FromSchema } from '@readme/api-core/types';
import type * as schemas from './schemas.js';

export type Addressobject = FromSchema<typeof schemas.Addressobject>;
export type Contact = FromSchema<typeof schemas.Contact>;
export type Contactobject = FromSchema<typeof schemas.Contactobject>;
export type Content = FromSchema<typeof schemas.Content>;
export type Document = FromSchema<typeof schemas.Document>;
export type Emailobject = FromSchema<typeof schemas.Emailobject>;
export type Image = FromSchema<typeof schemas.Image>;
export type LisMessageItemsObject = FromSchema<typeof schemas.LisMessageItemsObject>;
export type ListMessageGlobalButtonsObject = FromSchema<typeof schemas.ListMessageGlobalButtonsObject>;
export type ListMessageOptionObject = FromSchema<typeof schemas.ListMessageOptionObject>;
export type Listmessage = FromSchema<typeof schemas.Listmessage>;
export type Locationmessage = FromSchema<typeof schemas.Locationmessage>;
export type Nameobject = FromSchema<typeof schemas.Nameobject>;
export type Orgobject = FromSchema<typeof schemas.Orgobject>;
export type Phoneobject = FromSchema<typeof schemas.Phoneobject>;
export type PostMsgFormDataParam = FromSchema<typeof schemas.PostMsg.formData>;
export type PostMsgMetadataParam = FromSchema<typeof schemas.PostMsg.metadata>;
export type PostMsgResponse2XX = FromSchema<typeof schemas.PostMsg.response['2XX']>;
export type QuickReplyFile = FromSchema<typeof schemas.QuickReplyFile>;
export type QuickReplyImageContentObject = FromSchema<typeof schemas.QuickReplyImageContentObject>;
export type Quickreply = FromSchema<typeof schemas.Quickreply>;
export type Quickreplyfilecontent = FromSchema<typeof schemas.Quickreplyfilecontent>;
export type Quickreplyimage = FromSchema<typeof schemas.Quickreplyimage>;
export type Quickreplyoptions = FromSchema<typeof schemas.Quickreplyoptions>;
export type Sticker = FromSchema<typeof schemas.Sticker>;
export type Text = FromSchema<typeof schemas.Text>;
export type Urlobject = FromSchema<typeof schemas.Urlobject>;
export type Video = FromSchema<typeof schemas.Video>;
